[advisories]
version = 2

db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]

yanked = "deny"

ignore = [
  "RUSTSEC-2020-0168", # mach is unmaintained
  "RUSTSEC-2021-0139", # https://github.com/serai-dex/serai/228
  "RUSTSEC-2022-0061", # https://github.com/serai-dex/serai/227
  "RUSTSEC-2024-0370", # proc-macro-error is unmaintained
]

[licenses]
version = 2

allow = [
  # Effective public domain
  "CC0-1.0",
  "Unlicense",

  # Attribution required
  "MIT",
  "MITNFA",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "Unicode-DFS-2016",
  "OpenSSL",

  # Non-invasive copyleft
  "MPL-2.0",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "GPL-3.0 WITH Classpath-exception-2.0",
]

exceptions = [
  { allow = ["AGPL-3.0"], name = "wikiblocks-coins-pallet" },
  { allow = ["AGPL-3.0"], name = "wikiblocks-validator-sets-pallet" },

  { allow = ["AGPL-3.0"], name = "wikiblocks-runtime" },
  { allow = ["AGPL-3.0"], name = "wikiblocks-node" },
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
  { path = "LICENSE", hash = 0xbd0eed23 }
]

[bans]
multiple-versions = "warn"
wildcards = "warn"
highlight = "all"
deny = [ { name = "serde_derive", version = ">=1.0.172, <1.0.185" } ]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = [
  "https://github.com/serai-dex/substrate-bip39",
  "https://github.com/serai-dex/substrate",
]
